project:
  type: website
  output-dir: docs

website:
  title: "Bassim Eledath"
  site-url: https://bassimeledath.com
  description: "This is Bassim's technical blog"
  navbar:
    right:
      - text: Blog
        href: blog.qmd 
      - icon: github
        href: https://github.com/bassimeledath
      - icon: linkedin
        href: https://www.linkedin.com/in/bassim-eledath/
format:
  html:
    theme: cosmo
    css: styles.css




