project:
  type: website
  output-dir: docs

website:
  title: "Bassim Eledath"
  site-url: https://bassimeledath.com
  description: "This is Bassim's technical blog"
  google-analytics: G-YQRSW0BTG2
  navbar:
    right:
      - text: About
        href: index.qmd
      - text: Blog
        href: blog.qmd 
      - text: Projects
        href: projects.qmd
      - icon: github
        href: https://github.com/bassimeledath
format:
  html:
    theme: theme.scss




